/**
 * e2bExport.ts
 * -----------------------------------------------------------------------------
 * Serialises an approved PvCase to an ICH E2B(R3)-flavoured ICSR XML document.
 *
 * This is a SIMPLIFIED, human-readable representation that mirrors the E2B(R3)
 * data-element structure and codes. A production exporter must emit the full
 * HL7 ICSR (ISO 27953-2) message with the ICH-mandated wrapper, batch header,
 * OIDs and null-flavours, then validate against the official schema before
 * gateway submission. Use this as the mapping reference, not the final artifact.
 * -----------------------------------------------------------------------------
 */

import {
  CHARACTERISATION_E2B_CODE,
  OUTCOME_E2B_CODE,
  PROFESSION_E2B_CODE,
  SEX_E2B_CODE,
  type PvCase,
} from "@/types/pvCase";

function esc(value: string | number | undefined | null): string {
  if (value === undefined || value === null) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function el(tag: string, value: string | number | undefined, indent = 6): string {
  if (value === undefined || value === "" || value === null) return "";
  const pad = " ".repeat(indent);
  return `${pad}<${tag}>${esc(value)}</${tag}>\n`;
}

function bool(v: boolean): "true" | "false" {
  return v ? "true" : "false";
}

export function generateE2bXml(pvCase: PvCase): string {
  const { raw, patient, reporter, drugs, adverseEvents } = pvCase;
  const now = new Date().toISOString();
  const caseId = raw.worldwideId ?? raw.id;

  const reporterBlock = `    <primarysource>
${el("reportergivename", reporter.givenName)}${el("reporterfamilyname", reporter.familyName)}${el(
    "qualification",
    reporter.profession ? PROFESSION_E2B_CODE[reporter.profession] : undefined
  )}${el("reportercontact", reporter.contact)}${el("reportercountry", reporter.countryCode)}    </primarysource>\n`;

  const patientBlock = `    <patient>
${el("patientinitial", patient.initials)}${el(
    "patientonsetage",
    patient.age
  )}${el("patientonsetageunit", patient.ageUnit)}${el(
    "patientsex",
    patient.sex ? SEX_E2B_CODE[patient.sex] : undefined
  )}    </patient>\n`;

  const reactionBlocks = adverseEvents
    .map((ev) => {
      const s = ev.seriousness;
      return `    <reaction>
${el("primarysourcereaction", ev.descriptionAsReported)}${el(
        "reactionmeddrallt",
        ev.meddra?.llt
      )}${el("reactionmeddralltcode", ev.meddra?.lltCode)}${el(
        "reactionmeddrapt",
        ev.meddra?.pt
      )}${el("reactionmeddraptcode", ev.meddra?.ptCode)}${el(
        "reactionmeddraversionpt",
        ev.meddra?.meddraVersion
      )}${el("reactionstartdate", ev.onsetDate)}${el(
        "reactionoutcome",
        OUTCOME_E2B_CODE[ev.outcome ?? "unknown"]
      )}      <seriousness>
${el("seriousnessdeath", bool(s.death), 8)}${el(
        "seriousnesslifethreatening",
        bool(s.lifeThreatening),
        8
      )}${el("seriousnesshospitalization", bool(s.hospitalization), 8)}${el(
        "seriousnessdisabling",
        bool(s.disabling),
        8
      )}${el("seriousnesscongenitalanomali", bool(s.congenitalAnomaly), 8)}${el(
        "seriousnessother",
        bool(s.otherMedicallySignificant),
        8
      )}      </seriousness>
    </reaction>\n`;
    })
    .join("");

  const drugBlocks = drugs
    .map(
      (d) => `    <drug>
${el("drugcharacterization", CHARACTERISATION_E2B_CODE[d.characterisation])}${el(
        "medicinalproduct",
        d.brandName ?? d.genericName
      )}${el("activesubstancename", d.genericName)}${el(
        "drugdosagetext",
        d.dosageText
      )}${el("drugindication", d.indication)}    </drug>\n`
    )
    .join("");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ICH E2B(R3) ICSR — simplified representation generated by PV Copilot -->
<ichicsr lang="en">
  <ichicsrmessageheader>
    <messagetype>ichicsr</messagetype>
    <messageformatversion>2.1</messageformatversion>
    <messageformatrelease>2.0</messageformatrelease>
${el("messagedate", now, 4)}  </ichicsrmessageheader>
  <safetyreport>
${el("safetyreportid", caseId, 4)}${el("primarysourcecountry", reporter.countryCode, 4)}${el(
    "serious",
    bool(Object.values(pvCase.caseSeriousness).some(Boolean)),
    4
  )}${el("receivedate", raw.receivedAt, 4)}${el("fulfillexpeditecriteria", "1", 4)}
${reporterBlock}${patientBlock}${reactionBlocks}${drugBlocks}  </safetyreport>
</ichicsr>
`;
}
